# meals_reference.py
# ─────────────────────────────────────────────────────────────────────
# This file mirrors your meals table + meal_tags table in Supabase.
# When your DB is fully seeded, replace this with a real Supabase query.
# Each meal dict matches the column names in your schema exactly.
# ─────────────────────────────────────────────────────────────────────

MEALS = [
    # ── BREAKFAST ──────────────────────────────────────────────────
    {
        "meal_id": "m_001", "name": "Moong dal chilla",
        "calories": 280, "protein_g": 14, "carbs_g": 38, "fat_g": 7,
        "inflammation_score": 2, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["stress_recovery", "normal", "fat_burn"],
        "suitable_slots": ["breakfast", "snack"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_002", "name": "Oats with banana and nuts",
        "calories": 320, "protein_g": 10, "carbs_g": 52, "fat_g": 9,
        "inflammation_score": 2, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["performance", "normal", "muscle_repair"],
        "suitable_slots": ["breakfast"],
        "high_sodium": False, "high_sugar": False, "high_carb": True,
    },
    {
        "meal_id": "m_003", "name": "Poha with peanuts",
        "calories": 300, "protein_g": 8, "carbs_g": 48, "fat_g": 9,
        "inflammation_score": 3, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["normal", "fat_burn"],
        "suitable_slots": ["breakfast"],
        "high_sodium": False, "high_sugar": False, "high_carb": True,
    },
    {
        "meal_id": "m_004", "name": "Eggs and whole wheat toast",
        "calories": 350, "protein_g": 22, "carbs_g": 30, "fat_g": 12,
        "inflammation_score": 3, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "non-veg", "budget": "low",
        "tags": ["muscle_repair", "performance", "normal"],
        "suitable_slots": ["breakfast"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_005", "name": "Greek yogurt with seeds",
        "calories": 220, "protein_g": 18, "carbs_g": 20, "fat_g": 6,
        "inflammation_score": 1, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "veg", "budget": "mid",
        "tags": ["stress_recovery", "cortisol_buffer", "fat_burn"],
        "suitable_slots": ["breakfast", "snack"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_006", "name": "Upma with vegetables",
        "calories": 290, "protein_g": 7, "carbs_g": 46, "fat_g": 8,
        "inflammation_score": 3, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["normal", "fat_burn"],
        "suitable_slots": ["breakfast"],
        "high_sodium": False, "high_sugar": False, "high_carb": True,
    },

    # ── LUNCH ───────────────────────────────────────────────────────
    {
        "meal_id": "m_007", "name": "Dal rice with sabzi",
        "calories": 480, "protein_g": 18, "carbs_g": 72, "fat_g": 10,
        "inflammation_score": 2, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["normal", "stress_recovery", "fat_burn"],
        "suitable_slots": ["lunch"],
        "high_sodium": False, "high_sugar": False, "high_carb": True,
    },
    {
        "meal_id": "m_008", "name": "Chicken rice bowl",
        "calories": 520, "protein_g": 38, "carbs_g": 55, "fat_g": 10,
        "inflammation_score": 3, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "non-veg", "budget": "mid",
        "tags": ["muscle_repair", "performance", "normal"],
        "suitable_slots": ["lunch"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_009", "name": "Paneer tikka with roti",
        "calories": 550, "protein_g": 28, "carbs_g": 50, "fat_g": 20,
        "inflammation_score": 4, "recovery_impact": "medium",
        "prep_type": "restaurant", "diet_type": "veg", "budget": "mid",
        "tags": ["muscle_repair", "normal"],
        "suitable_slots": ["lunch"],
        "high_sodium": True, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_010", "name": "Rajma chawal",
        "calories": 500, "protein_g": 20, "carbs_g": 78, "fat_g": 8,
        "inflammation_score": 2, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["normal", "stress_recovery"],
        "suitable_slots": ["lunch"],
        "high_sodium": False, "high_sugar": False, "high_carb": True,
    },
    {
        "meal_id": "m_011", "name": "Grilled fish with salad",
        "calories": 420, "protein_g": 40, "carbs_g": 20, "fat_g": 14,
        "inflammation_score": 1, "recovery_impact": "high",
        "prep_type": "restaurant", "diet_type": "non-veg", "budget": "high",
        "tags": ["performance", "muscle_repair", "cortisol_buffer"],
        "suitable_slots": ["lunch"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_012", "name": "Quinoa vegetable bowl",
        "calories": 400, "protein_g": 16, "carbs_g": 58, "fat_g": 10,
        "inflammation_score": 1, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "vegan", "budget": "mid",
        "tags": ["stress_recovery", "cortisol_buffer", "fat_burn"],
        "suitable_slots": ["lunch"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_013", "name": "Chole bhature",
        "calories": 680, "protein_g": 18, "carbs_g": 90, "fat_g": 26,
        "inflammation_score": 7, "recovery_impact": "low",
        "prep_type": "restaurant", "diet_type": "veg", "budget": "mid",
        "tags": ["normal"],
        "suitable_slots": ["lunch"],
        "high_sodium": True, "high_sugar": False, "high_carb": True,
    },
    {
        "meal_id": "m_014", "name": "Tofu stir fry with brown rice",
        "calories": 420, "protein_g": 22, "carbs_g": 54, "fat_g": 12,
        "inflammation_score": 2, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "vegan", "budget": "mid",
        "tags": ["stress_recovery", "muscle_repair", "normal"],
        "suitable_slots": ["lunch"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },

    # ── SNACK ───────────────────────────────────────────────────────
    {
        "meal_id": "m_015", "name": "Mixed nuts and seeds",
        "calories": 180, "protein_g": 6, "carbs_g": 10, "fat_g": 14,
        "inflammation_score": 1, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "veg", "budget": "mid",
        "tags": ["cortisol_buffer", "stress_recovery", "fat_burn"],
        "suitable_slots": ["snack"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_016", "name": "Banana with peanut butter",
        "calories": 220, "protein_g": 6, "carbs_g": 34, "fat_g": 8,
        "inflammation_score": 2, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["performance", "muscle_repair", "normal"],
        "suitable_slots": ["snack"],
        "high_sodium": False, "high_sugar": True, "high_carb": True,
    },
    {
        "meal_id": "m_017", "name": "Sprouts chaat",
        "calories": 160, "protein_g": 10, "carbs_g": 24, "fat_g": 2,
        "inflammation_score": 1, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["fat_burn", "stress_recovery", "cortisol_buffer"],
        "suitable_slots": ["snack"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_018", "name": "Protein shake",
        "calories": 200, "protein_g": 28, "carbs_g": 12, "fat_g": 4,
        "inflammation_score": 2, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "non-veg", "budget": "high",
        "tags": ["muscle_repair", "performance"],
        "suitable_slots": ["snack"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_019", "name": "Fruit bowl",
        "calories": 150, "protein_g": 2, "carbs_g": 36, "fat_g": 1,
        "inflammation_score": 1, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "vegan", "budget": "low",
        "tags": ["stress_recovery", "cortisol_buffer", "fat_burn"],
        "suitable_slots": ["snack"],
        "high_sodium": False, "high_sugar": True, "high_carb": True,
    },

    # ── DINNER ──────────────────────────────────────────────────────
    {
        "meal_id": "m_020", "name": "Khichdi with ghee",
        "calories": 380, "protein_g": 14, "carbs_g": 60, "fat_g": 10,
        "inflammation_score": 2, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["stress_recovery", "normal", "fat_burn"],
        "suitable_slots": ["dinner"],
        "high_sodium": False, "high_sugar": False, "high_carb": True,
    },
    {
        "meal_id": "m_021", "name": "Grilled chicken with vegetables",
        "calories": 420, "protein_g": 42, "carbs_g": 18, "fat_g": 16,
        "inflammation_score": 2, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "non-veg", "budget": "mid",
        "tags": ["muscle_repair", "performance", "normal"],
        "suitable_slots": ["dinner"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_022", "name": "Palak dal with roti",
        "calories": 400, "protein_g": 18, "carbs_g": 55, "fat_g": 10,
        "inflammation_score": 1, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "veg", "budget": "low",
        "tags": ["stress_recovery", "cortisol_buffer", "muscle_repair"],
        "suitable_slots": ["dinner"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_023", "name": "Vegetable soup with bread",
        "calories": 280, "protein_g": 8, "carbs_g": 42, "fat_g": 6,
        "inflammation_score": 1, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "vegan", "budget": "low",
        "tags": ["stress_recovery", "cortisol_buffer", "fat_burn"],
        "suitable_slots": ["dinner"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_024", "name": "Fish curry with rice",
        "calories": 480, "protein_g": 36, "carbs_g": 52, "fat_g": 12,
        "inflammation_score": 2, "recovery_impact": "high",
        "prep_type": "home", "diet_type": "non-veg", "budget": "mid",
        "tags": ["muscle_repair", "performance", "normal"],
        "suitable_slots": ["dinner"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
    {
        "meal_id": "m_025", "name": "Methi thepla with curd",
        "calories": 340, "protein_g": 12, "carbs_g": 48, "fat_g": 10,
        "inflammation_score": 2, "recovery_impact": "medium",
        "prep_type": "home", "diet_type": "jain", "budget": "low",
        "tags": ["normal", "stress_recovery"],
        "suitable_slots": ["breakfast", "dinner"],
        "high_sodium": False, "high_sugar": False, "high_carb": False,
    },
]

# Slot calorie targets (approximate proportion of daily target)
SLOT_CALORIE_FRACTION = {
    "breakfast": 0.25,
    "lunch":     0.35,
    "snack":     0.10,
    "dinner":    0.30,
}
